vti_encoding:SR|utf8-nl
vti_timelastmodified:TR|26 Mar 2017 12:29:29 -0000
vti_extenderversion:SR|12.0.0.0
vti_backlinkinfo:VX|admin/report2.php admin/index.php admin/report_olx_customers.php admin/day_by_stock.php admin/customer_master.php admin/enquire_list.php admin/list_by_user.php admin/subcrib_master.php admin/_subcat_master.php admin/report_stock.php admin/customer_master_new.php admin/setting_service_master.php admin/report_stock2.php admin/order_track.php admin/repair_master.php admin/search.php admin/timeline.php admin/approv_dis.php admin/cust_add.php admin/dashboard.php admin/offer_master.php admin/order.php admin/feedback_list.php admin/dealer_master.php admin/order_details.php admin/report_activity.php admin/stock_detail.php admin/repair_list.php admin/utilities.php admin/report_order_summary.php form_new.php admin/tabs.php admin/banner-mgmt.php admin/report.php form_used_demo.php admin/change_status_master.php admin/update_profile.php admin/user.php admin/offer-mgmt.php admin/report_order_summary_dtl.php admin/enq_detail.php admin/order2.php admin/feedback_master.php admin/invoice.php admin/subsubcat_master.php admin/report1.php admin/extra-dashboard.php form_used_old.php admin/customer_master_sanjay.php admin/dashboard_sunil.php admin/datepicker.php admin/newsletter_master.php 2form_used.php admin/feedback_detail.php form1.php admin/_offer_master.php admin/report_services.php admin/financer_master.php admin/repair_center_master.php admin/repair_dtl.php admin/phone_detail.php form_used_sanjay.php admin/customer_master_old_pawan.php admin/mail_greeting.php admin/walking_user.php admin/cupon_master.php admin/track_order.php admin/dealer_master_new.php admin/phone_detail_sunil.php admin/enquiry_master.php admin/form_elements.php admin/page1.php admin/subcat_master.php admin/chat.php admin/extra2.php admin/greeting_master.php admin/_toDelete_register.php admin/banner_master.php admin/new_save.php
vti_author:SR|DESKTOP-E44UKRN\\User
vti_modifiedby:SR|DESKTOP-E44UKRN\\User
vti_timecreated:TR|26 Mar 2017 12:29:29 -0000
vti_cacheddtm:TX|26 Mar 2017 12:29:29 -0000
vti_filesize:IR|1721
