vti_encoding:SR|utf8-nl
vti_timelastmodified:TR|11 Apr 2017 03:08:03 -0000
vti_extenderversion:SR|12.0.0.0
vti_backlinkinfo:VX|view_cart.php detail_sunil.php admin/report_olx_customers.php admin/customer_master_new.php admin/setting_service_master.php admin/subcrib_master.php admin/_subcat_master.php admin/customer_master.php admin/enquire_list.php admin/report_stock.php admin/report_stock2.php admin/cust_add.php admin/order_track.php admin/search.php admin/timeline.php admin/approv_dis.php admin/dashboard.php admin/feedback_list.php admin/offer_master.php admin/order.php dealer_dashboard.php old_thanks.php product_status.php view_cart_old_new.php admin/report_activity.php admin/stock_detail.php admin/dealer_master.php admin/order_details.php customer_dashboard.php admin/utilities.php admin/repair_list.php admin/report_order_summary.php dealer_dashboard_old.php admin/banner-mgmt.php admin/change_status_master.php admin/report.php admin/tabs.php admin/enq_detail.php admin/offer-mgmt.php admin/order2.php admin/update_profile.php admin/user.php admin/report_order_summary_dtl.php customer_dashboard_old.php detail.php login.php admin/feedback_master.php admin/invoice.php admin/report1.php admin/subsubcat_master.php form_used_old.php admin/customer_master_sanjay.php admin/extra-dashboard.php admin/dashboard_sunil.php admin/datepicker.php admin/feedback_detail.php admin/newsletter_master.php admin/sanjay_1.php old_order_detail2.php admin/_offer_master.php admin/financer_master.php admin/repair_center_master.php admin/report_services.php review_old.php admin/customer_master_old_pawan.php admin/mail_greeting.php admin/phone_detail.php admin/repair_dtl.php admin/walking_user.php checkout_backup.php admin/cupon_master.php admin/dealer_master_new.php admin/phone_detail_sunil.php admin/track_order.php detail_old.php admin/chat.php admin/enquiry_master.php admin/form_elements.php admin/page1.php admin/subcat_master.php login_old.php admin/extra2.php admin/greeting_master.php admin/new_save.php admin/_toDelete_register.php admin/banner_master.php order_detail2_old.php admin/report2.php view_cart_old.php admin/day_by_stock.php admin/index.php admin/list_by_user.php
vti_author:SR|pawan-PC\\pawan
vti_modifiedby:SR|pawan-PC\\pawan
vti_timecreated:TR|29 May 2017 06:51:17 -0000
vti_cacheddtm:TX|29 May 2017 06:51:17 -0000
vti_filesize:IR|119459
